# GitHub Pages Configuration for Lawnomic
title: Lawnomic - EU Privacy Compliance Audit Tool
description: Professional GDPR compliance auditing tool. Scan your website for privacy risks, third-party trackers, and consent management issues.
url: "https://lawnomic.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Theme
theme: minima

# SEO
author: Lawnomic Team
twitter:
  username: lawnomic
  card: summary_large_image

# Social media
social_links:
  twitter: lawnomic
  github: lawnomic
  linkedin: lawnomic

# Analytics (replace with your tracking ID)
google_analytics: G-XXXXXXXXXX

# Exclude files from Jekyll build
exclude:
  - lawnomic/
  - venv/
  - requirements.txt
  - manage.py
  - README.md
  - .gitignore
  - .env
  - reports/

# Include important files
include:
  - _pages
  - assets

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag